# Site Settings
locale                   : "en-US"
title                    : "jsnomad"
title_separator          : "-"
subtitle                 : "immad"
name                     : "lIIlllIIIIlI"
description              : "mad"
url                      : "https://lIIlllIIIIlInomad.github.io".
baseurl                  : ""
